// remote-react/src/components/Counter.tsx
import { useState } from "react";
import "../styles/index.css";

export default function Counter() {
  const [count, setCount] = useState(0);
  return (
    <div className="p-5 border-2 border-[#61dafb] rounded-xl bg-[#e8f7fd] max-w-xs">
      <p className="mb-3">
        Count number: <strong>{count}</strong>
      </p>
      <button
        onClick={() => setCount((c) => c + 1)}
        className="px-4 py-2 bg-[#61dafb] border-none rounded-md cursor-pointer font-bold hover:opacity-80 transition-opacity"
      >
        + Plus
      </button>
    </div>
  );
}

// remote-vue/src/components/Counter.vue
<template>
  <div class="vue-counter">
    <p>
      Count: <strong>{{ count }}</strong>
    </p>
    <button @click="count++">+ Plus</button>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";

const count = ref(0);
</script>

<style scoped>
.vue-card {
  padding: 20px;
  border: 2px solid #42b883;
  border-radius: 10px;
  background: #e8fdf2;
  max-width: 320px;
}
h3 {
  margin: 0 0 12px;
  color: #2a7a52;
}
p {
  margin: 0 0 12px;
}
button {
  padding: 8px 16px;
  background: #42b883;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  font-weight: bold;
  color: white;
}
button:hover {
  background: #33a06f;
}
</style>
